on: [push]

name: AzurePowerShellSample

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
  steps:
    - name: Sample Azure action
      with: # Set Azure credentials secret as an input
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
      env: # Or as an environment variable
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzResource -ResourceGroupName "365_2"
        azPSVersion: '3.1.0'

